.TH PEPSTER 1
.SH NAME
pepster \- a discord bot for osu!
.SH SYNOPSIS
pepster is a bot
.SH OPTIONS
.TP
.BR \-conf\ \fIfile\fR
Set the path to the configuration file to use. If this option is not specified, or the file doesn't exist, a configuration file will be generated for you in the current directory.
.TP
.BR \-cmd\fR
Starts pepster in "command-line mode", where it will prompt for actions, giving the user the ability to execute arbitrary commands as the bot from the terminal.

